application: ainyday
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /img
  static_dir: public/img

- url: /admin
  script: rainyday.py
  login: admin

- url: /.*
  script: rainyday.py

